[package]
name = "rr-rs"
version = "0.0.1"
authors = ["Cassandra McCarthy <cassie@7596ff.com>"]
edition = "2018"
description = "A discord bot that does many things besides change the server icon occasionally."
readme = "README.md"
repository = "https://github.com/7596ff/rr-rs"
license-file = "LICENSE"
default-run = "rr-rs"

[dev-dependencies]
rusty-hook = "0.11.1"

[dependencies]
# base
anyhow = "1.0"
dotenv = "0.15"
log = "0.4"
pretty_env_logger = "0.4"
tokio = "0.2"
# discord
base64 = "0.12"
chrono = "0.4"
futures-util = "0.3"
image = "0.23"
isahc = "0.9"
lazy_static = { version = "1.4", default-features = false }
rand = "0.7"
rarity-permission-calculator = { branch = "main", default-features = false, git = "https://github.com/rarity-rs/permission-calculator" }
serde = "1.0"
serde_json = "1.0"
shellwords = { version = "1.1", default-features = false }
twilight = { branch = "trunk", git = "https://github.com/twilight-rs/twilight.git", default-features = false, features = [ "builders", "cache", "gateway", "http", "model", "standby", "rustls" ] }
# db
darkredis = "0.7"
postgres = "0.17"
refinery = { version = "0.3", default-features = false, features = [ "postgres" ] }
sqlx = { version = "0.3", default-features = false, features = [ "runtime-tokio", "macros", "postgres", "chrono" ] }

[[bin]]
name = "migrate_icons"
test = false
bench = false
