[package]
name = "rr-rs"
version = "0.0.1"
authors = ["Cassandra McCarthy <cassie@7596ff.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15"
log = "0.4"
pretty_env_logger = "0.4"
serenity = { git = "https://github.com/serenity-rs/serenity", rev = "d2b19a27128e80ad298bc87414d6cb0a10060bc6" }
anyhow = "1.0"
