[package]
name = "rr-rs"
version = "0.0.1"
authors = ["Cassandra McCarthy <cassie@7596ff.com>"]
edition = "2018"
description = "A discord bot that does many things besides change the server icon occasionally."
readme = "README.md"
repository = "https://github.com/7596ff/rr-rs"
license-file = "LICENSE"

[dependencies]
anyhow = "1.0"
chrono = "0.4.11"
dotenv = "0.15"
log = "0.4"
pretty_env_logger = "0.4"
rand = "0.7.3"
tokio = "0.2.21"

[dependencies.twilight]
git = "https://github.com/twilight-rs/twilight.git"
