[package]
name = "rr-rs"
version = "0.0.1"
authors = ["Cassandra McCarthy <cassie@7596ff.com>"]
edition = "2018"
description = "A discord bot that does many things besides change the server icon occasionally."
readme = "README.md"
repository = "https://github.com/7596ff/rr-rs"
license-file = "LICENSE"

[dev-dependencies]
rusty-hook = "0.11.1"

[dependencies]
# base
anyhow = "1.0"
dotenv = "0.15"
log = "0.4"
pretty_env_logger = "0.4"
tokio = "0.2.21"
# discord
twilight = { git = "https://github.com/twilight-rs/twilight.git" }
# commands
chrono = "0.4.11"
rand = "0.7.3"
# db
postgres = "0.17.3"
refinery = { version = "0.3.0", default-features = false, features = [ "postgres" ] }
sqlx = { version = "0.3.5", default-features = false, features = [ "runtime-tokio", "macros",
"postgres", "chrono" ] }
